### ISSUE TITLE
Facing assertion error while running json2xlsx test.ts -l -j test.json -o output.xlsx

### ISSUE THREAD

**Issue by tarun29061990** [mkasa/json2xlsx#3]
When running json2xlsx test.ts -l -j test.json -o output.xlsx
Traceback (most recent call last):
  File "/Users/tarunchaudhary/venv/bin/json2xlsx", line 7, in <module>
    from json2xlsx.utilities.json2xlsx import main
  File "/Users/tarunchaudhary/venv/lib/python3.6/site-packages/json2xlsx/utilities/json2xlsx.py", line 27
    print "Assertion Error: Missing .asList()?", type(d2), type([])
                                              ^
SyntaxError: invalid syntax

**Comment by shaminti** [comment]
was this fixed ?? @tarun29061990  @mkasa

**Comment by bubnenkoff** [comment]
Same problem
