### ISSUE TITLE
getting the same assertion

### ISSUE THREAD

**Issue by shaminti** [mkasa/json2xlsx#5]
Traceback (most recent call last):
  File "/usr/bin/json2xlsx", line 11, in <module>
    load_entry_point('json2xlsx==1.3', 'console_scripts', 'json2xlsx')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/temp/json2xlsx/json2xlsx/utilities/json2xlsx.py", line 27
    print "Assertion Error: Missing .asList()?", type(d2), type([])
                                              ^
SyntaxError: invalid syntax

**Comment by AdmAlexus** [comment]
Maybe the problem is in the installed version of the Python? Try using 2.x

> Traceback (most recent call last):
> File "/usr/bin/json2xlsx", line 11, in 
> load_entry_point('json2xlsx==1.3', 'console_scripts', 'json2xlsx')()
> File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 476, in load_entry_point
> return get_distribution(dist).load_entry_point(group, name)
> File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2700, in load_entry_point
> return ep.load()
> File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2318, in load
> return self.resolve()
> File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2324, in resolve
> module = **import**(self.module_name, fromlist=['**name**'], level=0)
> File "/root/temp/json2xlsx/json2xlsx/utilities/json2xlsx.py", line 27
> print "Assertion Error: Missing .asList()?", type(d2), type([])
> ^
> SyntaxError: invalid syntax

Maybe the problem is in the installed version of the Python? Try using 2.x
